[target.x86_64-elf]
rustflags = [
    "-C", "linker=rust-lld",
    "-C", "linker-flavor=ld.lld",
    "-C", "force-frame-pointers=yes",
    "-C", "code-model=large",
    "-C", "relocation-model=static"
]
